title: Minimal theme
logo: https://raw.githubusercontent.com/enerle/enerle.github.io/main/fig.jpeg
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
